# Cloudflare Pages configuration
# Note: This file is primarily for local development with wrangler pages dev
# Production deployment is handled by Cloudflare Pages GitHub integration

name = "letool-bess-arbitrage"
compatibility_date = "2024-01-01"

# Pages Functions configuration is automatic
# Functions are placed in /functions directory