name = "nem-harvester"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/2 * * * *"]   # every 2 minutes for live updates

[[r2_buckets]]
binding = "NEM_R2"
bucket_name = "nem-data"

[[d1_databases]]
binding = "DB"
database_name = "nem-meta-1754738882"
database_id = "de4c149e-a61c-4eed-ae3f-d033a557cd80"

# No Queues on free plan - using D1 job system instead